name: 'Compile QCDLOOP'
description: 'QCDLOOP'
inputs:
  who-to-greet:  # id of input
    description: 'Set something'
    required: true
    default: 'Hi !'
outputs:
  time: # id of output
    description: 'Some result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
